# ????
server:
  port: 3000

# mysql??
spring:
  datasource:
    url: jdbc:mysql:///chatonline
    username: root
    password: xty510521
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

# mybatis-plus???
mybatis-plus:
  type-aliases-package: com.ncu.chatserver
  global-config:
    db-config:
      #      logic-delete-field: isDeleted  #??????
      id-type: auto #???????